disabled_rules:
  - trailing_whitespace
  - todo
opt_in_rules:
  - empty_count
  - empty_string
  - force_cast
  - force_try
  - function_body_length
excluded:
  - Carthage
  - Pods
  - SwiftLint
  - Tests
  - OctaneRunner
line_length: 120
