import Foundation

/// Centralized constants for the OctaneLog application.
public enum AppConstants {
    
    public enum Narrative {
        public static let processingTag = "Processing"
        public static let autoGeneratedTag = "Auto-Generated"
        public static let newTag = "New"
        public static let defaultTheme = "Discovery"
        public static let recurringCharacterCoffeeShop = "The Coffee Shop"
        public static let coffeeKeyword = "Coffee"
        
        public static let offlineModeSummary = "Offline Mode: Just another day on the asphalt. (Check API Key for the full story)."
    }
    
    public enum UI {
        public static let appName = "OCTANELOG"
        public static let waitingForVideo = "WAITING FOR VIDEO SOURCE"
        public static let rec = "REC"
        public static let standby = "STANDBY"
        public static let checking = "CHECKING..."
        public static let sceneCheck = "SCENE CHECK"
        public static let endDrive = "END DRIVE"
        public static let startDrive = "START DRIVE"
        public static let debugTest = "DEBUG TEST"
        public static let aiSystem = "AI SYSTEM"
        public static let online = "ONLINE"
        public static let geminiVision = "GEMINI VISION"
    }
    
    public enum Config {
        public static let episodeRecapSuffixCount = 15
        public static let weeklyRecapIntervalDays = 7
    }
}
